### ISSUE TITLE
Notice: Undefined variable: current in _system/content.php on line 78

### ISSUE THREAD

**Issue by abr4xas** [askonomm/dynamite#14]
Hi there, 

```php
return array($current);
```

I don't know why but, i have this error

```php
Notice: Undefined variable: current in _system/content.php on line 78
```

**Comment by askonomm** [comment]
I'll see if I can reproduce it!

Do you have any content? Does it occur when there's no content, or if the URL is wrong, or what?

**Comment by abr4xas** [comment]
thank you, but... Now, i have "Page not found", i have a boom-goes-the-dynamite.md in `_content` folder

**Comment by askonomm** [comment]
@abr4xas could you tell me what PHP version are you running? The [dynamite.dashy.me](http://dynamite.dashy.me) site is running on 100% the code in the repository, and it's working fine, which makes me think there's a issue with server configuration. I recommend PHP 5.5+, but it _should_ work with PHP 5.4 as well.

Also, I think it might be related to the [`glob`](http://php.net/manual/en/function.glob.php) function, because it's not supported by some variants of PHP 5.4.

**Comment by abr4xas** [comment]
```bash
php -v
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```
`var_dump($_SERVER);`
http://pastebin.com/BsAqNd0n

`phpinfo();`
http://pastebin.com/WcDtZ0ce

**Comment by askonomm** [comment]
Found the problem! Seems like your `REQUEST_URI` is `/server.php`, but Dynamite has no such file. Dynamite rewrites `/path` with mod_rewrite to index.php, which it uses later on. So the problem is at your server configuration (localhost, I assume). The REQUEST_URI should not be a php file at all, and you need to have mod_rewrite enabled in Apache configuration.

**Comment by abr4xas** [comment]
`var_dump($_SERVER);` from `index.php`
http://pastebin.com/V31YaQrB

**Comment by askonomm** [comment]
Alright, it seems it didn't want to work in a subfolder. [Get the master branch zip](https://github.com/askonomm/dynamite/archive/master.zip) and try now, it should be resolved.

**Comment by abr4xas** [comment]
Thank you very much... :smile:
